service:
  name: serverless-book-shop
plugins:
  - serverless-webpack
  #les 2 plugins ajoutés ici servent à faire la validation en utilisant les fchiers dans le modele.
  #il faut installer ses plugin en utilisant les commandes npm install serverless-aws-documentation serverless-reqvalidator-plugin --save-dev
  - serverless-reqvalidator-plugin #npm install serverless-reqvalidator-plugin
  - serverless-aws-documentation #npm install serverless-aws-documentation
  #Optimzation if our lambda function
  - serverless-plugin-canary-deployments
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-iam-roles-per-function
    #npm i --save serverless-plugin-canary-deployments
    #npm install --save serverless-dynamodb-local
    #npm install serverless-offline --save-dev
  #This plugin allows to restrict permissions for just one of your function npm i --save-dev serverless-roles-per-function

  
#Added for lambda optimzation
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

# ici on fournit les stages qui peuvent etre dev, prod etc... Ici dev est utilisé par defaut quand on ne fournit pas d'autres stages..
#la region aussi peut etre forunie sinon on va déplyer dans la région par defaut us-east-1
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

#Added for making tracing the log for lambda and apiGateway 
  tracing:
    lambda: true
    apiGateway: true
    iamRoleStatements:
      - Effect: 'Allow' # xray permissions (required)
        Action:
          - 'xray:PutTraceSegments'
          - 'xray:PutTelemetryRecords'
        Resource:
          - '*'
#definition des variables d'environnements (nom de la table est fournit comme variable d'environnement)
  environment:
    CATEGORIES_TABLE: Categories-${self:provider.stage}
    BOOKS_TABLE: Books-${self:provider.stage}
  
    BOOK_ID_INDEX: BookIdIndex
   
    BOOKS_S3_BUCKET: serverless-cloud-udagram-books-ourobadiou-${self:provider.stage}
   
    SIGNED_URL_EXPIRATION: 300
    CONNECTIONS_TABLE: Connections-${self:provider.stage}
  
#custom est utilisé pour la validation des données avant l'envoi au serveur pour utiliser la fonction lambda
custom:
  topicName: imagesTopic-${self:provider.stage}
  documentation:
    api:
      info:
        version: v1.0.0
        title: Udagram API
        description: Serverless application for book corver
    models:
      - name: CategorieRequest
        contentType: application/json
        schema: ${file(models/create-categorie-request.json)}
      - name: BookRequest
        contentType: application/json
        schema: ${file(models/create-book-request.json)}



#Définition de la liste de toutes les fonctions

# fonction pour recupérer la liste des categories
functions:
  #Appel de la fonction lambda auth0Authorizer
  RS256Auth:
    handler: src/lambda/auth/rs256Auth0Authorizer.handler

  GetCategories:
    handler: src/lambda/http/getCategories.handler
    events:
      - http:
          method: get
          path: categories
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATEGORIES_TABLE}

# fonction pour créer un categorie
  CreateCategorie:
    handler: src/lambda/http/createCategorie.handler
    events:
      - http:
          method: post
          path: categories
          cors: true
          # this allow to do Authorization by token
          #authorizer: Auth ici on utilise HS256
          authorizer: RS256Auth #ici on utilise RS256 avec le fichier rs256Auth0Authorizer et la focntion déclarée dans ce fichier
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new categorie
            description: Create a new categorie
            requestModels:
              'application/json': CategorieRequest #the same name like custom models
    iamRoleStatements:
      - Effect: Allow
        Action:
          #iamrole pour utiliser Post vers une base de données DynamoDB
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CATEGORIES_TABLE}

# fonction pour recupérer liste des books par categorie en passant en categories/1/books(c'est la liste des Books de la Categorie 1)
  GetBooks:
    handler: src/lambda/http/getBooks.handler
    events:
      - http:
          method: get
          path: categories/{categorieId}/books
          cors: true
          
    iamRoleStatements:
      - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BOOKS_TABLE}/index/${self:provider.environment.BOOK_ID_INDEX}
      - Effect: Allow
      Action:
        - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BOOKS_TABLE}
    
#fonction pour créer une Book
  CreateBook:
    handler: src/lambda/http/createBook.handler
    events:
      - http:
          method: post
          path: categories/{categorieId}/books
          cors: true
          # this allow to do Authorization by token
           #authorizer: Auth ici on utilise HS256
          authorizer: RS256Auth #ici on utilise RS256 avec le fichier rs256Auth0Authorizer et la focntion déclarée dans ce fichier
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new books
            description: Create a new books
            requestModels:
              'application/json': BookRequest #the same name like custom models
    iamRoleStatements:
      - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BOOKS_TABLE}/index/${self:provider.environment.BOOK_ID_INDEX}
      - Effect: Allow 
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:provider.environment.BOOKS_S3_BUCKET}/*'
    
 
# fonction pour recupérer une Book
  GetBook:
    handler: src/lambda/http/getBook.handler
    events:
      - http:
          method: get
          path: books/{bookId}
          cors: true
    iamRoleStatements:
      - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMAGES_TABLE}/index/${self:provider.environment.IMAGE_ID_INDEX}

resources:
  Resources:
    #ressource to make authorization
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    ####################################################""
    CategoriesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CATEGORIES_TABLE}


    BooksDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: categorieId
            AttributeType: S
          - AttributeName: bookId
            AttributeType: S
        KeySchema:
          - AttributeName: categorieId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.BOOK_ID_INDEX} 
            KeySchema:
            - AttributeName: bookId
              KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.BOOKS_TABLE}
    
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BOOKS_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
         
  ###########################################################
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.BOOKS_S3_BUCKET}/*'
        Bucket: !Ref AttachmentsBucket
    ########################################################